name: Reusable Workflow Example
description: >
  This reusable action simplifies the process of packaging
  NuGet packages and publishing them to GitHub.

inputs:
  dotnet_version:
    description: "Version of .NET SDK to use (e.g., '10.x')"
    required: true
  project_path:
    description: "Path to the .NET project file (e.g., 'project/project.csproj')"
    required: true
  package_output:
    description: "Output directory for the NuGet package (e.g., 'project/bin/Release')"
    required: true
  package_version:
    description: "Version of the NuGet package to publish (e.g., '1.0.0')"
    required: true
  assembly_version:
    description: "(Optional) Set specific assembly version (e.g., '1.0.0'). If not set, it will default to package version."
  github_pat:
    description: "GitHub Personal Access Token with 'write:packages' scope"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout files
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
      with:
        dotnet-version: ${{ inputs.dotnet_version }}

    - name: Install dependencies
      env:
        PROJECT_PATH: ${{ inputs.project_path }}
      shell: pwsh
      run: dotnet restore "$env:PROJECT_PATH"

    - name: Build
      env:
        PROJECT_PATH: ${{ inputs.project_path }}
      shell: pwsh
      run: dotnet build "$env:PROJECT_PATH" --configuration Release --no-restore

    - name: Create NuGet Package
      env:
        PROJECT_PATH: ${{ inputs.project_path }}
        PACKAGE_OUTPUT: ${{ inputs.package_output }}
        PACKAGE_VERSION: ${{ inputs.package_version }}
        ASSEMBLY_VERSION: ${{ inputs.assembly_version || inputs.package_version }}
      shell: pwsh
      run: dotnet pack "$env:PROJECT_PATH" --configuration Release --no-build --output "$env:PACKAGE_OUTPUT" /p:PackageVersion="$env:PACKAGE_VERSION" /p:Version="$env:ASSEMBLY_VERSION" --verbosity minimal

    - name: Add GitHub NuGet source
      env:
        NUGET_PASSWORD: ${{ inputs.github_pat }}
        REPOSITORY_OWNER: ${{ github.repository_owner }}
      shell: pwsh
      run: dotnet nuget add source --username "$env:GITHUB_ACTOR" --password "$env:NUGET_PASSWORD" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/$env:REPOSITORY_OWNER/index.json"

    - name: Publish NuGet Package
      shell: pwsh
      env:
        PACKAGE_OUTPUT: ${{ inputs.package_output }}
        NUGET_PASSWORD: ${{ inputs.github_pat }}
      run: |
        Get-ChildItem $env:PACKAGE_OUTPUT -Filter *.nupkg | ForEach-Object {
          dotnet nuget push $_.FullName `
            --source "github" `
            --api-key $env:NUGET_PASSWORD `
            --skip-duplicate
        }
